import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ConnectButton } from '@rainbow-me/rainbowkit'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          <a href="https://nextjs.org">Web3 Demo App</a><br></br>
        </h2>
        <h3>Cross-Chain Wallet Functionality</h3>

        <ConnectButton />

        <p className={styles.description}>
        by Eric Prouty
        </p>

      
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Prouty Interactive{' '}
        </a>
      </footer>
    </div>
  )
}
